---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qk2gfmw4ollu/public_html/wp-content/themes/gardenofeydie
    # - /bin/cp -r * $DEPLOYPATH
    - /bin/cp page-lifestyle.php $DEPLOYPATH
    - /bin/cp /css/custom.css $DEPLOYPATH
    - /bin/cp css/custom.css $DEPLOYPATH
    - /bin/cp template-parts/reusable-content.php $DEPLOYPATH
    - /bin/cp template-parts/subscribe.php $DEPLOYPATH
